-- begin PRC_APPUNTAMENTI
alter table PRC_APPUNTAMENTI add constraint FK_PRC_APPUNTAMENTI_ON_CLIENTE foreign key (CLIENTE_ID) references PRC_CLIENTI(ID)^
alter table PRC_APPUNTAMENTI add constraint FK_PRC_APPUNTAMENTI_ON_OPERATORE foreign key (OPERATORE_ID) references PRC_OPERATORI(ID)^
create index IDX_PRC_APPUNTAMENTI_ON_CLIENTE on PRC_APPUNTAMENTI (CLIENTE_ID)^
create index IDX_PRC_APPUNTAMENTI_ON_OPERATORE on PRC_APPUNTAMENTI (OPERATORE_ID)^
-- end PRC_APPUNTAMENTI
-- begin PRC_SEDUTA
alter table PRC_SEDUTA add constraint FK_PRC_SEDUTA_ON_CLIENTE foreign key (CLIENTE_ID) references PRC_CLIENTI(ID)^
create index IDX_PRC_SEDUTA_ON_CLIENTE on PRC_SEDUTA (CLIENTE_ID)^
-- end PRC_SEDUTA
-- begin PRC_OPERATORI
alter table PRC_OPERATORI add constraint FK_PRC_OPERATORI_ON_UTENTE foreign key (UTENTE_ID) references SEC_USER(ID)^
create index IDX_PRC_OPERATORI_ON_UTENTE on PRC_OPERATORI (UTENTE_ID)^
-- end PRC_OPERATORI

-- begin PRC_SEDUTA_SERVIZI
alter table PRC_SEDUTA_SERVIZI add constraint FK_PRC_SEDUTA_SERVIZI_ON_SEDUTA foreign key (SEDUTA_ID) references PRC_SEDUTA(ID)^
alter table PRC_SEDUTA_SERVIZI add constraint FK_PRC_SEDUTA_SERVIZI_ON_SERVIZIO foreign key (SERVIZIO_ID) references PRC_SERVIZI(ID)^
alter table PRC_SEDUTA_SERVIZI add constraint FK_PRC_SEDUTA_SERVIZI_ON_OPERATORE foreign key (OPERATORE_ID) references PRC_OPERATORI(ID)^
create index IDX_PRC_SEDUTA_SERVIZI_ON_SEDUTA on PRC_SEDUTA_SERVIZI (SEDUTA_ID)^
create index IDX_PRC_SEDUTA_SERVIZI_ON_SERVIZIO on PRC_SEDUTA_SERVIZI (SERVIZIO_ID)^
create index IDX_PRC_SEDUTA_SERVIZI_ON_OPERATORE on PRC_SEDUTA_SERVIZI (OPERATORE_ID)^
-- end PRC_SEDUTA_SERVIZI
-- begin PRC_CLIENTI
alter table PRC_CLIENTI add constraint FK_PRC_CLIENTI_ON_COMUNE_CODICEISTAT foreign key (COMUNE_CODICEISTAT) references PCBB_BASE_COMUNI(codice_istat)^
create index IDX_PRC_CLIENTI_ON_COMUNE_CODICEISTAT on PRC_CLIENTI (COMUNE_CODICEISTAT)^
-- end PRC_CLIENTI
