alter table PRC_SEDUTA_SERVIZI add constraint FK_PRC_SEDUTA_SERVIZI_ON_SEDUTA foreign key (SEDUTA_ID) references PRC_SEDUTA(ID);
alter table PRC_SEDUTA_SERVIZI add constraint FK_PRC_SEDUTA_SERVIZI_ON_SERVIZIO foreign key (SERVIZIO_ID) references PRC_SERVIZI(ID);
alter table PRC_SEDUTA_SERVIZI add constraint FK_PRC_SEDUTA_SERVIZI_ON_OPERATORE foreign key (OPERATORE_ID) references PRC_OPERATORI(ID);
create index IDX_PRC_SEDUTA_SERVIZI_ON_SEDUTA on PRC_SEDUTA_SERVIZI (SEDUTA_ID);
create index IDX_PRC_SEDUTA_SERVIZI_ON_SERVIZIO on PRC_SEDUTA_SERVIZI (SERVIZIO_ID);
create index IDX_PRC_SEDUTA_SERVIZI_ON_OPERATORE on PRC_SEDUTA_SERVIZI (OPERATORE_ID);
