alter table PRC_CLIENTI add constraint FK_PRC_CLIENTI_ON_COMUNE_CODICEISTAT foreign key (COMUNE_CODICEISTAT) references PCBB_BASE_COMUNI(codice_istat);
create index IDX_PRC_CLIENTI_ON_COMUNE_CODICEISTAT on PRC_CLIENTI (COMUNE_CODICEISTAT);
