alter table PRC_APPUNTAMENTI add constraint FK_PRC_APPUNTAMENTI_ON_CLIENTE foreign key (CLIENTE_ID) references PRC_CLIENTI(ID);
alter table PRC_APPUNTAMENTI add constraint FK_PRC_APPUNTAMENTI_ON_OPERATORE foreign key (OPERATORE_ID) references PRC_OPERATORI(ID);
create index IDX_PRC_APPUNTAMENTI_ON_CLIENTE on PRC_APPUNTAMENTI (CLIENTE_ID);
create index IDX_PRC_APPUNTAMENTI_ON_OPERATORE on PRC_APPUNTAMENTI (OPERATORE_ID);
